# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o2tvseries', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_url',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='episode',
            name='file_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='episode',
            name='referrer_link',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='episode',
            name='save_location',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_url',
            field=models.CharField(max_length=255),
        ),
    ]
