# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 20:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o2tvseries', '0002_o2tvseries'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='episode_no',
            field=models.IntegerField(null=True),
        ),
    ]
