# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-21 23:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o2tvseries', '0003_o2tvseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='download_timestamp',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_title',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='episode_url',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='file_format',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='file_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='file_size',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='referrer_link',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='episode',
            name='save_location',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
