# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-10-22 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('o2tvseries', '0006_o2tvseries'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='episode_title',
            field=models.CharField(db_index=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='season_no',
            field=models.IntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='season',
            name='title',
            field=models.CharField(db_index=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='show',
            name='title',
            field=models.CharField(db_index=True, max_length=255, unique=True),
        ),
    ]
